export const MOCK_PATIENTS = [
  {
    id: "pat-001",
    firstName: "Thembi",
    lastName: "Nkosi",
    idNumber: "8901015000086",
    dateOfBirth: "1989-01-01",
    gender: "FEMALE",
    phone: "071 234 5678",
    email: "thembi.nkosi@email.com",
    scheme: "Discovery Health",
    membershipNumber: "DH1234567",
    planOption: "Executive",
    outstandingBalance: 0,
    status: "active",
    lastVisit: "2026-04-25",
  },
  {
    id: "pat-002",
    firstName: "James",
    lastName: "van der Merwe",
    idNumber: "7504205000081",
    dateOfBirth: "1975-04-20",
    gender: "MALE",
    phone: "082 345 6789",
    email: "james.vdm@email.com",
    scheme: "Bonitas",
    membershipNumber: "BON9876543",
    planOption: "BonSave",
    outstandingBalance: 750.00,
    status: "active",
    lastVisit: "2026-04-25",
  },
  {
    id: "pat-003",
    firstName: "Fatima",
    lastName: "Patel",
    idNumber: "9203085000085",
    dateOfBirth: "1992-03-08",
    gender: "FEMALE",
    phone: "083 456 7890",
    email: "fatima.patel@email.com",
    scheme: "GEMS",
    membershipNumber: "GEMS5678901",
    planOption: "Beryl",
    outstandingBalance: 0,
    status: "active",
    lastVisit: "2026-04-25",
  },
  {
    id: "pat-004",
    firstName: "Lungelo",
    lastName: "Dube",
    idNumber: "8807105000083",
    dateOfBirth: "1988-07-10",
    gender: "MALE",
    phone: "076 567 8901",
    email: null,
    scheme: "Cash Patient",
    membershipNumber: null,
    planOption: null,
    outstandingBalance: 1250.00,
    status: "active",
    lastVisit: "2026-04-25",
  },
  {
    id: "pat-005",
    firstName: "Maria",
    lastName: "Santos",
    idNumber: "9506215000084",
    dateOfBirth: "1995-06-21",
    gender: "FEMALE",
    phone: "084 678 9012",
    email: "maria.santos@email.com",
    scheme: "Momentum Health",
    membershipNumber: "MOM2345678",
    planOption: "Ingwe",
    outstandingBalance: 0,
    status: "active",
    lastVisit: "2026-04-22",
  },
  {
    id: "pat-006",
    firstName: "Robert",
    lastName: "Khumalo",
    idNumber: "6801015000089",
    dateOfBirth: "1968-01-01",
    gender: "MALE",
    phone: "072 789 0123",
    email: "r.khumalo@email.com",
    scheme: "Medihelp",
    membershipNumber: "MH3456789",
    planOption: "Dimension",
    outstandingBalance: 3400.00,
    status: "active",
    lastVisit: "2026-04-18",
  },
  {
    id: "pat-007",
    firstName: "Ayanda",
    lastName: "Zulu",
    idNumber: "9912155000082",
    dateOfBirth: "1999-12-15",
    gender: "FEMALE",
    phone: "063 890 1234",
    email: "ayanda.zulu@email.com",
    scheme: "Discovery Health",
    membershipNumber: "DH4567890",
    planOption: "KeyCare Plus",
    outstandingBalance: 0,
    status: "active",
    lastVisit: "2026-04-15",
  },
  {
    id: "pat-008",
    firstName: "Priya",
    lastName: "Naicker",
    idNumber: "8503255000087",
    dateOfBirth: "1985-03-25",
    gender: "FEMALE",
    phone: "079 901 2345",
    email: "priya.naicker@email.com",
    scheme: "Fedhealth",
    membershipNumber: "FED5678901",
    planOption: "flexiFED 4",
    outstandingBalance: 980.50,
    status: "active",
    lastVisit: "2026-04-10",
  },
]

export const MOCK_INVOICES = [
  {
    id: "inv-001",
    invoiceNumber: "INV-20260425-00014",
    patientId: "pat-001",
    patientName: "Thembi Nkosi",
    scheme: "Discovery Health",
    dateOfService: "2026-04-25",
    total: 850.00,
    medicalAidClaimed: 850.00,
    patientLiable: 0,
    outstanding: 0,
    status: "SUBMITTED",
  },
  {
    id: "inv-002",
    invoiceNumber: "INV-20260425-00013",
    patientId: "pat-002",
    patientName: "James van der Merwe",
    scheme: "Bonitas",
    dateOfService: "2026-04-25",
    total: 750.00,
    medicalAidClaimed: 0,
    patientLiable: 750.00,
    outstanding: 750.00,
    status: "DRAFT",
  },
  {
    id: "inv-003",
    invoiceNumber: "INV-20260424-00012",
    patientId: "pat-003",
    patientName: "Fatima Patel",
    scheme: "GEMS",
    dateOfService: "2026-04-24",
    total: 1200.00,
    medicalAidClaimed: 1200.00,
    patientLiable: 0,
    outstanding: 0,
    status: "PAID",
  },
  {
    id: "inv-004",
    invoiceNumber: "INV-20260424-00011",
    patientId: "pat-004",
    patientName: "Lungelo Dube",
    scheme: "Cash Patient",
    dateOfService: "2026-04-24",
    total: 1250.00,
    medicalAidClaimed: 0,
    patientLiable: 1250.00,
    outstanding: 1250.00,
    status: "PARTIALLY_PAID",
  },
  {
    id: "inv-005",
    invoiceNumber: "INV-20260423-00010",
    patientId: "pat-006",
    patientName: "Robert Khumalo",
    scheme: "Medihelp",
    dateOfService: "2026-04-18",
    total: 980.00,
    medicalAidClaimed: 980.00,
    patientLiable: 0,
    outstanding: 0,
    status: "REJECTED",
  },
  {
    id: "inv-006",
    invoiceNumber: "INV-20260420-00009",
    patientId: "pat-008",
    patientName: "Priya Naicker",
    scheme: "Fedhealth",
    dateOfService: "2026-04-10",
    total: 980.50,
    medicalAidClaimed: 980.50,
    patientLiable: 0,
    outstanding: 980.50,
    status: "SUBMITTED",
  },
]

export const MOCK_CLAIMS = [
  {
    id: "clm-001",
    invoiceId: "inv-001",
    invoiceNumber: "INV-20260425-00014",
    patientName: "Thembi Nkosi",
    scheme: "Discovery Health",
    submittedAt: "2026-04-25 09:12",
    switchRef: "DISC-2026042509120001",
    amount: 850.00,
    status: "SUBMITTED",
    rejectionCode: null,
    rejectionReason: null,
  },
  {
    id: "clm-002",
    invoiceId: "inv-003",
    invoiceNumber: "INV-20260424-00012",
    patientName: "Fatima Patel",
    scheme: "GEMS",
    submittedAt: "2026-04-24 14:30",
    switchRef: "GEMS-2026042414300001",
    amount: 1200.00,
    status: "ACCEPTED",
    rejectionCode: null,
    rejectionReason: null,
  },
  {
    id: "clm-003",
    invoiceId: "inv-005",
    invoiceNumber: "INV-20260423-00010",
    patientName: "Robert Khumalo",
    scheme: "Medihelp",
    submittedAt: "2026-04-18 10:05",
    switchRef: "MHLP-2026041810050001",
    amount: 980.00,
    status: "REJECTED",
    rejectionCode: "05",
    rejectionReason: "Prior authorisation was required and not obtained",
  },
  {
    id: "clm-004",
    invoiceId: "inv-006",
    invoiceNumber: "INV-20260420-00009",
    patientName: "Priya Naicker",
    scheme: "Fedhealth",
    submittedAt: "2026-04-10 11:45",
    switchRef: "FED-2026041011450001",
    amount: 980.50,
    status: "SUBMITTED",
    rejectionCode: null,
    rejectionReason: null,
  },
]

export const REJECTION_CODES: Record<string, string> = {
  "01": "Patient not found on medical aid - check membership number",
  "02": "Patient membership is not active on date of service",
  "03": "Treatment code not covered by this plan",
  "04": "Annual benefit limit has been reached",
  "05": "Prior authorisation was required and not obtained",
  "06": "Claim is a duplicate of one already received",
  "07": "Waiting period applies - patient has not completed their waiting period",
  "08": "Doctor practice number is incorrect or not recognised",
  "09": "ICD-10 code is invalid or not applicable to the treatment code",
  "10": "Claim is outside the 4-month submission deadline",
  "23": "Savings account balance insufficient - patient liable",
  "UNKNOWN": "Claim was rejected - contact the medical aid for details",
}

export const TARIFF_CODES = [
  { code: "0190", description: "Consultation, surgery, new patient", nrpl: 485.00, requiresICD10: true },
  { code: "0191", description: "Consultation, surgery, repeat patient", nrpl: 365.00, requiresICD10: true },
  { code: "0192", description: "Consultation, extended, new patient", nrpl: 620.00, requiresICD10: true },
  { code: "0193", description: "Consultation, extended, repeat patient", nrpl: 510.00, requiresICD10: true },
  { code: "0100", description: "Home visit, surgery hours", nrpl: 680.00, requiresICD10: true },
  { code: "0102", description: "Home visit, after hours", nrpl: 890.00, requiresICD10: true },
  { code: "0120", description: "Consultation, after hours, surgery", nrpl: 540.00, requiresICD10: true },
  { code: "0121", description: "Consultation, after hours, extended", nrpl: 740.00, requiresICD10: true },
  { code: "0135", description: "Telephonic consultation", nrpl: 220.00, requiresICD10: true },
  { code: "0136", description: "Video consultation / Telemedicine", nrpl: 280.00, requiresICD10: true },
  { code: "0162", description: "Minor surgical procedure", nrpl: 850.00, requiresICD10: true },
  { code: "0185", description: "Injection (therapeutic)", nrpl: 145.00, requiresICD10: true },
  { code: "0186", description: "Infusion (IV drip setup)", nrpl: 310.00, requiresICD10: true },
  { code: "4081", description: "ECG with report", nrpl: 380.00, requiresICD10: true },
  { code: "6115", description: "Removal of sutures", nrpl: 175.00, requiresICD10: true },
]

export const ICD10_CODES = [
  { code: "Z00.0", description: "General adult medical examination" },
  { code: "J06.9", description: "Acute upper respiratory infection, unspecified" },
  { code: "J45.9", description: "Asthma, unspecified" },
  { code: "I10", description: "Essential (primary) hypertension" },
  { code: "E11.9", description: "Type 2 diabetes mellitus without complications" },
  { code: "J18.9", description: "Pneumonia, unspecified organism" },
  { code: "K21.0", description: "Gastro-oesophageal reflux disease with oesophagitis" },
  { code: "M54.5", description: "Low back pain" },
  { code: "F32.9", description: "Major depressive disorder, single episode, unspecified" },
  { code: "A09", description: "Other and unspecified gastroenteritis" },
  { code: "N39.0", description: "Urinary tract infection" },
  { code: "B34.9", description: "Viral infection, unspecified" },
  { code: "L30.9", description: "Dermatitis, unspecified" },
  { code: "R50.9", description: "Fever, unspecified" },
  { code: "Z34.0", description: "Supervision of normal first pregnancy" },
]

export const MEDICAL_AID_SCHEMES = [
  { id: "sch-1",  name: "Discovery Health",               shortCode: "DISCOVERY",  mediSwitchDestCode: "DISC",  supportsRealTime: true },
  { id: "sch-2",  name: "Government Employees Medical Scheme (GEMS)", shortCode: "GEMS", mediSwitchDestCode: "GEMS", supportsRealTime: true },
  { id: "sch-3",  name: "Bonitas",                        shortCode: "BONITAS",    mediSwitchDestCode: "BON",   supportsRealTime: true },
  { id: "sch-4",  name: "Momentum Health",                shortCode: "MOMENTUM",   mediSwitchDestCode: "MOM",   supportsRealTime: false },
  { id: "sch-5",  name: "Medihelp",                       shortCode: "MEDIHELP",   mediSwitchDestCode: "MHLP",  supportsRealTime: false },
  { id: "sch-6",  name: "Fedhealth",                      shortCode: "FEDHEALTH",  mediSwitchDestCode: "FED",   supportsRealTime: false },
  { id: "sch-7",  name: "Bestmed",                        shortCode: "BESTMED",    mediSwitchDestCode: "BEST",  supportsRealTime: false },
  { id: "sch-8",  name: "Profmed",                        shortCode: "PROFMED",    mediSwitchDestCode: "PROF",  supportsRealTime: false },
  { id: "sch-9",  name: "Sizwe",                          shortCode: "SIZWE",      mediSwitchDestCode: "SIZ",   supportsRealTime: false },
  { id: "sch-10", name: "CompCare",                       shortCode: "COMPCARE",   mediSwitchDestCode: "COMP",  supportsRealTime: false },
  { id: "sch-11", name: "Resolution Health",              shortCode: "RESOLUTION", mediSwitchDestCode: "RES",   supportsRealTime: false },
  { id: "sch-12", name: "Polmed",                         shortCode: "POLMED",     mediSwitchDestCode: "POL",   supportsRealTime: false },
  { id: "sch-13", name: "Keyhealth",                      shortCode: "KEYHEALTH",  mediSwitchDestCode: "KEY",   supportsRealTime: false },
  { id: "sch-14", name: "LA Health",                      shortCode: "LAHEALTH",   mediSwitchDestCode: "LAH",   supportsRealTime: false },
  { id: "sch-15", name: "PG Group",                       shortCode: "PGGROUP",    mediSwitchDestCode: "PGG",   supportsRealTime: false },
  { id: "sch-16", name: "Selfmed",                        shortCode: "SELFMED",    mediSwitchDestCode: "SELF",  supportsRealTime: false },
  { id: "sch-17", name: "Transmed",                       shortCode: "TRANSMED",   mediSwitchDestCode: "TRANS", supportsRealTime: false },
  { id: "sch-18", name: "Old Mutual Health",              shortCode: "OMHEALTH",   mediSwitchDestCode: "OMH",   supportsRealTime: false },
  { id: "sch-19", name: "Bankmed",                        shortCode: "BANKMED",    mediSwitchDestCode: "BANK",  supportsRealTime: false },
  { id: "sch-20", name: "Hosmed",                         shortCode: "HOSMED",     mediSwitchDestCode: "HOS",   supportsRealTime: false },
]

// 20 common GP medicines — Section 14 seed data
export const NAPPI_CODES = [
  { nappiCode: "707482001", productName: "Amoxil 500mg Capsules",         genericName: "Amoxicillin",          strength: "500mg",     dosageForm: "Capsule",  packSize: "24",  schedule: "S4", sepPrice: 52.40 },
  { nappiCode: "701258001", productName: "Augmentin 625mg Tablets",       genericName: "Amox/Clav acid",       strength: "625mg",     dosageForm: "Tablet",   packSize: "21",  schedule: "S4", sepPrice: 198.70 },
  { nappiCode: "713842001", productName: "Panado 500mg Tablets",          genericName: "Paracetamol",          strength: "500mg",     dosageForm: "Tablet",   packSize: "24",  schedule: "S0", sepPrice: 23.50 },
  { nappiCode: "708121001", productName: "Voltaren 50mg Tablets",         genericName: "Diclofenac sodium",    strength: "50mg",      dosageForm: "Tablet",   packSize: "30",  schedule: "S3", sepPrice: 68.90 },
  { nappiCode: "710543001", productName: "Prednisone 5mg Tablets",        genericName: "Prednisone",           strength: "5mg",       dosageForm: "Tablet",   packSize: "28",  schedule: "S4", sepPrice: 34.20 },
  { nappiCode: "702991001", productName: "Ciprobay 500mg Tablets",        genericName: "Ciprofloxacin",        strength: "500mg",     dosageForm: "Tablet",   packSize: "10",  schedule: "S4", sepPrice: 89.60 },
  { nappiCode: "714620001", productName: "Zithromax 500mg Tablets",       genericName: "Azithromycin",         strength: "500mg",     dosageForm: "Tablet",   packSize: "3",   schedule: "S4", sepPrice: 112.30 },
  { nappiCode: "716834001", productName: "Nexium 20mg Capsules",          genericName: "Esomeprazole",         strength: "20mg",      dosageForm: "Capsule",  packSize: "28",  schedule: "S3", sepPrice: 149.80 },
  { nappiCode: "703812001", productName: "Concor 5mg Tablets",            genericName: "Bisoprolol",           strength: "5mg",       dosageForm: "Tablet",   packSize: "30",  schedule: "S4", sepPrice: 78.40 },
  { nappiCode: "709234001", productName: "Norvasc 5mg Tablets",           genericName: "Amlodipine",           strength: "5mg",       dosageForm: "Tablet",   packSize: "30",  schedule: "S4", sepPrice: 92.60 },
  { nappiCode: "711820001", productName: "Glucophage 850mg Tablets",      genericName: "Metformin",            strength: "850mg",     dosageForm: "Tablet",   packSize: "30",  schedule: "S4", sepPrice: 44.10 },
  { nappiCode: "717345001", productName: "Lipitor 20mg Tablets",          genericName: "Atorvastatin",         strength: "20mg",      dosageForm: "Tablet",   packSize: "30",  schedule: "S4", sepPrice: 125.70 },
  { nappiCode: "712901001", productName: "Ventolin 100mcg Inhaler",       genericName: "Salbutamol",           strength: "100mcg",    dosageForm: "Inhaler",  packSize: "200", schedule: "S3", sepPrice: 82.30 },
  { nappiCode: "706543001", productName: "Flixotide 125mcg Inhaler",      genericName: "Fluticasone",          strength: "125mcg",    dosageForm: "Inhaler",  packSize: "120", schedule: "S4", sepPrice: 210.60 },
  { nappiCode: "718120001", productName: "Allergex 4mg Tablets",          genericName: "Chlorphenamine",       strength: "4mg",       dosageForm: "Tablet",   packSize: "30",  schedule: "S1", sepPrice: 29.80 },
  { nappiCode: "705678001", productName: "Stilpane Syrup 200ml",          genericName: "Paracetamol/Codeine",  strength: "120/8mg/5ml", dosageForm: "Syrup", packSize: "200ml", schedule: "S3", sepPrice: 54.90 },
  { nappiCode: "719234001", productName: "Ponstan 500mg Capsules",        genericName: "Mefenamic acid",       strength: "500mg",     dosageForm: "Capsule",  packSize: "24",  schedule: "S3", sepPrice: 67.40 },
  { nappiCode: "704123001", productName: "Losartan 50mg Tablets",         genericName: "Losartan potassium",   strength: "50mg",      dosageForm: "Tablet",   packSize: "30",  schedule: "S4", sepPrice: 56.20 },
  { nappiCode: "720543001", productName: "Doxycycline 100mg Capsules",    genericName: "Doxycycline",          strength: "100mg",     dosageForm: "Capsule",  packSize: "10",  schedule: "S4", sepPrice: 48.60 },
  { nappiCode: "721890001", productName: "Flagyl 200mg Tablets",          genericName: "Metronidazole",        strength: "200mg",     dosageForm: "Tablet",   packSize: "21",  schedule: "S4", sepPrice: 38.90 },
]

// Mock benefit checks for patient detail page
export const MOCK_BENEFIT_CHECKS = [
  {
    id: "bc-001",
    patientId: "pat-001",
    scheme: "Discovery Health",
    membershipNumber: "DH1234567",
    performedAt: "2026-04-25 08:45",
    status: "SUCCESS",
    isActiveMember: true,
    planOption: "Executive",
    savingsAvailable: 8420.50,
    dayToDayAvailable: 3200.00,
    hospitalAvailable: null,
  },
  {
    id: "bc-002",
    patientId: "pat-001",
    scheme: "Discovery Health",
    membershipNumber: "DH1234567",
    performedAt: "2026-03-12 09:15",
    status: "SUCCESS",
    isActiveMember: true,
    planOption: "Executive",
    savingsAvailable: 12640.00,
    dayToDayAvailable: 5800.00,
    hospitalAvailable: null,
  },
  {
    id: "bc-003",
    patientId: "pat-003",
    scheme: "GEMS",
    membershipNumber: "GEMS5678901",
    performedAt: "2026-04-24 13:55",
    status: "SUCCESS",
    isActiveMember: true,
    planOption: "Beryl",
    savingsAvailable: 4100.00,
    dayToDayAvailable: 2100.00,
    hospitalAvailable: null,
  },
]

// Mock payments for patient detail page
export const MOCK_PATIENT_PAYMENTS = [
  {
    id: "pay-001",
    patientId: "pat-001",
    invoiceId: "inv-001",
    invoiceNumber: "INV-20260425-00014",
    paymentType: "MEDICAL_AID",
    amount: 850.00,
    reference: "DISC-PAY-20260425",
    paymentDate: "2026-04-25",
    scheme: "Discovery Health",
    status: "ALLOCATED",
  },
  {
    id: "pay-002",
    patientId: "pat-003",
    invoiceId: "inv-003",
    invoiceNumber: "INV-20260424-00012",
    paymentType: "MEDICAL_AID",
    amount: 1200.00,
    reference: "GEMS-PAY-20260424",
    paymentDate: "2026-04-24",
    scheme: "GEMS",
    status: "ALLOCATED",
  },
  {
    id: "pay-003",
    patientId: "pat-004",
    invoiceId: "inv-004",
    invoiceNumber: "INV-20260424-00011",
    paymentType: "PATIENT_CASH",
    amount: 500.00,
    reference: "CASH-REC-001",
    paymentDate: "2026-04-24",
    scheme: null,
    status: "PARTIALLY_ALLOCATED",
  },
]
